repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: flake8
      args:
        - --max-line-length=99
    - id: check-ast
    - id: check-case-conflict
    - id: debug-statements
    - id: double-quote-string-fixer
    - id: end-of-file-fixer
- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: 'v2.0.4'
  hooks:
  -  id: autopep8
     args:
       - --in-place
       - --max-line-length=99
# We run pylint from local env, to ensure modules can be found
- repo: local
  hooks:
    - id: pylint
      name: pylint
      entry: python3 -m pylint.__main__
      language: system
      types: [python]
      args:
        - --disable=broad-except
        - --disable=consider-using-f-string
        - --disable=invalid-name
        - --disable=missing-docstring
        - --disable=no-else-raise
        - --disable=protected-access
        - --disable=too-many-branches
        - --disable=too-many-lines
        - --disable=too-many-locals
        - --disable=too-many-public-methods
        - --disable=too-many-statements
        - --disable=undefined-loop-variable
        - --disable=unspecified-encoding
        - --include-naming-hint=yes
        - --max-args=10
        - --max-locals=25
        - --max-returns=10
